### ISSUE TITLE
Installing json Api

### ISSUE THREAD

**Issue by BBirlison** [creativetimofficial/ct-vue-paper-dashboard-pro-laravel#1]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [+] I am running the latest version
- [+] I checked the documentation and found no answer
- [+] I checked to make sure that this issue has not already been filed
- [+ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Trying to install the API, but I keep getting errors.

# Current Behavior

Lots of wrong version of laravel errors

# Failure Information (for bugs)

I have tried running under Laravel v8.0 and v7.3

Could you confirm the target version of the components needed to install?

## Steps to Reproduce

follow the document steps following the document steps.
get error at the composer install step

## Context

* Operating System: W10
* Browser and Version: Chrome Version 88.0.4324.150 (Official Build) (64-bit)

**Comment by teamupdivision** [comment]
Hi @BBirlison,

Thanks for using Creative Tim products.

Could you please let us know what is the PHP server you are using? 
 
Thank you.

**Comment by BBirlison** [comment]
Hi, 

I am using apache via XAMPP, running both their V7.3 and V8

I started with their v8.0.2 version that runs PHP 8.0.2 and then downgraded to

XAMPP v7.3.27-0 / 7.4.15-0
runnning

PHP 7.3.27 , 7.4.15
Apache 2.4.46
MariaDB 10.4.17
Perl 5.32.1
OpenSSL 1.1.1i (UNIX only)
phpMyAdmin 5.0.4

**Comment by teamupdivision** [comment]
Hi @BBirlison,

Thank you for the details. Would you be kind to share with us:   

1. a screenshot of what you get with the “php -v” command in the command line where you run "composer install" 
  2. a screenshot of the errors you receive in the console when you try to install

We think it may help a lot in getting a better understanding of the issue. 

Thanks,
UPDIVISION Team

**Comment by BBirlison** [comment]
Hi, 

Since I sent the message I decided to remove absolutely everything (again) and restart from the zip file.

It seems much happier now and I don't understand why, its the same zip file and the same build of Xampp using v7.3

I get a couple of warnings and an error but not 27 wrong versions of php..

![image](https://user-images.githubusercontent.com/62951395/107968966-f88a4e80-6fa6-11eb-919b-eee027ea0b6b.png)

many thanks

Brian

**Comment by BBirlison** [comment]
Morning, 

Fixed it... installed under PHP7.3 and seems to run. Not sure what it was doing, the fresh build worked once I had updated composer.

all the best 
Brian

**Comment by teamupdivision** [comment]
Good morning Brian,

We're glad to hear this is fixed now. If there is anything else we can help with, please let us know.

Also, if you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). 

Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).

Best,
UPDIVISION Team
