### ISSUE TITLE
Lost, i'm sure it is something I have done

### ISSUE THREAD

**Issue by BBirlison** [creativetimofficial/ct-vue-paper-dashboard-pro-laravel#2]
Hi, 

I'm having a little issue getting dashboard to run beyond the initial log in screen it just returns a failed to authenticate message

I don't quite understand where the json API resides and how it runs.. the install seems successful.

Chrome has lots of errors but the most fundamental one seems to be: 
xhr.js?b50d:177 POST http://localhost:8000/api/v1/login net::ERR_CONNECTION_REFUSED

How do I find its correct address (i used 3000 per the example then changed it to 8000)
Is the Json API part of the laravel database, part of the dashboard or standalone, Do I need to run the Json APi?

regards

Brian

**Comment by teamupdivision** [comment]
@BBirlison Hi Brian, 

The Laravel JSON:API project requires a working Apache/Nginx local environment with PHP, Composer and MySQL.

If you don't already have a local development environment, use one of the following links:

Windows: How to install WAMP on Windows (https://updivision.com/blog/post/beginner-s-guide-to-setting-up-your-local-development-environment-on-windows)
Linux: How to install LAMP on Linux (https://howtoubuntu.org/how-to-install-lamp-on-ubuntu)
Mac: How to install MAMP on MAC (https://wpshout.com/quick-guides/how-to-install-mamp-on-your-mac)

Install Composer: https://getcomposer.org/doc/00-intro.md

Please let us know if this helped. 

Best,
UPDIVISION Team

**Comment by BBirlison** [comment]
Umm am running XAmpp environment.

but I still have the problem that i don't know how to find where my json API is, so i can't be sure that .etc file of the dashboard points to it. How do I find it, once I have followed the steps in the docuementation?

Does running the dashboard's npm run dev start the API? is it part of the laravel?

many thanks

Brian

**Comment by teamupdivision** [comment]
Hi Brian, @BBirlison 

In the .env file from the API project, it should be correlated with the APP_URL (For example: APP_URL=http://laravel-json-api.test/), while in .env file on front it will be connected to the API through VUE_APP_API_BASE_URL (for exemple: VUE_APP_API_BASE_URL=http://laravel-json-api.test/api/v1)
 
You may also find a few more details under this paragraph of the documentation:
Create a new .env file: cp .env.example .env
VUE_APP_BASE_URL should contain the URL of your Vue Paper Dashboard Project (eg. http://localhost:8080/)
VUE_APP_API_BASE_URL should contain the URL of your Laravel JSON:API Project. (eg. http://localhost:3000/api/v1)

Please let us know if this helped. 

Best,
UPDIVISION Team

**Comment by BBirlison** [comment]
Not really..

I have read the doc material, i'm still missing something.

How do I know what the URL's are.
when I npm run dev - I get the URL for the APP part

It may seem an obvious question but how do I get the same thing for the API?
The documentation doesn't seem discuss the structure or the link between it and the APP.

regards
Brian

**Comment by teamupdivision** [comment]
Hey Brian, @BBirlison 

Are you using '**php artisan serve**' to run the API?

If so, please use a proper multi-threaded web server such as Apache or Nginx to serve the backend application. Do not use php artisan serve as it will result in stalled requests due to the single-threaded nature of the built-in PHP web server. We strongly recommend using Laradock or Laragon if possible.

Best,
UPDIVISION Team

**Comment by BBirlison** [comment]
thanks, 

I tried php artisan serve to run it locally and as it didn't work decided I was doing something wrong.

I'll get one of your two suggestions up and running and see if that makes it all beter.
Just for total clarity I should 
1, run the API via laradock or laragon
2, run the app via npm run dev

many thanks

Brian

**Comment by teamupdivision** [comment]
Hey Brian, @BBirlison 

Yes, we confirm these are the steps to be followed. 

Thanks,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi Brian, 

Hope this solved the problem. Please let us know if there is anything else we can help with. 

Best,
UPDIVISION Team

**Comment by BBirlison** [comment]
Hi sorry,Yes I have it working now.. it took a while to work out how to configure laragon.Many thanksBrianSent from my Galaxy
-------- Original message --------From: Updivision Team <notifications@github.com> Date: 05/03/2021  12:40  (GMT+00:00) To: creativetimofficial/ct-vue-paper-dashboard-pro-laravel <ct-vue-paper-dashboard-pro-laravel@noreply.github.com> Cc: BBirlison <brian@cloudclimb.co.uk>, Mention <mention@noreply.github.com> Subject: Re: [creativetimofficial/ct-vue-paper-dashboard-pro-laravel] Lost, i'm sure it is something I have done (#2) 
Hi Brian,
Hope this solved the problem. Please let us know if there is anything else we can help with.
Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hey Brian, 

We're glad to hear that! Please feel free to contact us if there are any other issues. 

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
