### ISSUE TITLE
Internal Server Error - 500

### ISSUE THREAD

**Issue by VigneshRM93** [creativetimofficial/ct-vue-paper-dashboard-pro-laravel#3]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Login

# Current Behavior

Tried to login but got "Internal Server Error". Able to register new user without any problem.

# Failure Information (for bugs)

{
    "errors": [
        {
            "status": "500",
            "title": "Internal Server Error"
        }
    ]
}

# Log file
[log.txt](https://github.com/creativetimofficial/ct-vue-paper-dashboard-pro-laravel/files/8403681/log.txt)

**Comment by teamupdivision** [comment]
Hi @VigneshRM93,

Thank you for reporting this issue and for using Creative Tim products.
 
We were not able to reproduce the error. Could you please let us know if you get this only on front or only on API? Is it for all login requests or only for the accounts you created? Also, could you please let us know if you did any updates on the code and if you did, what were these updates?
 
All the best,
UPDIVISION Team

**Comment by VigneshRM93** [comment]
Getting this error on both front end and api for all accounts. No i haven't made any update on the code.

**Comment by teamupdivision** [comment]
Hi @VigneshRM93,

Could you also send the .env for both the frontend and backend, please? This will help a lot in investigating further.

Best,
UPDIVISION Team

**Comment by VigneshRM93** [comment]
[laravel env.txt](https://github.com/creativetimofficial/ct-vue-paper-dashboard-pro-laravel/files/8456306/laravel.env.txt)
[vue.env.txt](https://github.com/creativetimofficial/ct-vue-paper-dashboard-pro-laravel/files/8456309/vue.env.txt)

**Comment by teamupdivision** [comment]
Hi @VigneshRM93,

Thank you very much for sharing this.

Could you please double-check if all the installation steps for the API setup project were followed? It looks like the APP_KEY is missing. Please generate application key: php artisan key:generate 

Here are a few more details that may help: https://vue-paper-dashboard-pro-laravel.creative-tim.com/documentation/examples/api-instalation.html#prerequisites

Please let us know if this helped and if you need any other information.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment]
Hi @VigneshRM93,

Is everything working properly now? We hope that the information we provided was helpful in solving your issue.

If you have any other questions, do not hesitate to let us know.

Best,
UPDIVISION Team

**Comment by javaswapdevelopment** [comment]
I get the same error 500 but my log is a little different:

[2022-05-11 04:10:22] local.ERROR: Attempt to read property "id" on null {"exception":"[object] (ErrorException(code: 0): Attempt to read property \"id\" on null at /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/app/Http/Controllers/Api/V1/Auth/LoginController.php:32)
[stacktrace]
#0 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/app/Http/Controllers/Api/V1/Auth/LoginController.php(32): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Api\\V1\\Auth\\LoginController->__invoke()
#3 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#4 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#5 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#6 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#7 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#8 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/app/Http/Middleware/JsonApi.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\JsonApi->handle()
#10 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#12 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(126): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(62): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#14 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#15 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#17 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#18 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#19 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#20 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#21 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#22 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()
#24 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#26 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#27 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#29 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#30 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#32 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#34 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#36 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#38 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#39 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#40 /home/slayer/Documents/codigos/daniel/clone-lol/lol-vue/laravel-json-api-pro/server.php(21): require_once('...')
#41 {main}
"}
